// 由 scripts/generate_resource_registry.py 自动生成, 请勿手工修改。
export const resourceRegistry = {
  schema_version: 1,
  registry_version: 1,
  permissions: [
    {
      code: "workspace.overview.access",
      resource_type: "page",
      action: "access",
      scope: "workspace",
      status: "active",
    },
    {
      code: "workspace.members.access",
      resource_type: "page",
      action: "access",
      scope: "workspace",
      status: "active",
    },
    {
      code: "organization.structure.access",
      resource_type: "page",
      action: "access",
      scope: "workspace",
      status: "active",
    },
    {
      code: "system.runtime.access",
      resource_type: "page",
      action: "access",
      scope: "workspace",
      status: "active",
    },
    {
      code: "enterprise.workspace.create",
      resource_type: "workspace",
      action: "create",
      scope: "account",
      status: "active",
    },
    {
      code: "enterprise.invitation.accept",
      resource_type: "workspace_invitation",
      action: "accept",
      scope: "account",
      status: "active",
    },
    {
      code: "workspace.context.switch",
      resource_type: "workspace",
      action: "switch",
      scope: "workspace",
      status: "active",
    },
    {
      code: "workspace.membership.leave",
      resource_type: "workspace_membership",
      action: "leave",
      scope: "workspace",
      status: "active",
    },
    {
      code: "workspace.member.invite",
      resource_type: "workspace_member",
      action: "invite",
      scope: "workspace",
      status: "active",
    },
    {
      code: "workspace.member.read",
      resource_type: "workspace_member",
      action: "read",
      scope: "workspace",
      status: "active",
    },
    {
      code: "workspace.member.disable",
      resource_type: "workspace_member",
      action: "disable",
      scope: "resource",
      status: "active",
    },
    {
      code: "workspace.entitlement.read",
      resource_type: "workspace_entitlement",
      action: "read",
      scope: "workspace",
      status: "active",
    },
    {
      code: "workspace.open_api.manage",
      resource_type: "workspace_feature",
      action: "manage",
      scope: "workspace",
      status: "active",
    },
    {
      code: "organization.department.create",
      resource_type: "department",
      action: "create",
      scope: "workspace",
      status: "active",
    },
    {
      code: "organization.department.read",
      resource_type: "department",
      action: "read",
      scope: "workspace",
      status: "active",
    },
    {
      code: "organization.department.move",
      resource_type: "department",
      action: "move",
      scope: "resource",
      status: "active",
    },
    {
      code: "organization.department.status",
      resource_type: "department",
      action: "change_status",
      scope: "resource",
      status: "active",
    },
    {
      code: "organization.position.create",
      resource_type: "position",
      action: "create",
      scope: "workspace",
      status: "active",
    },
    {
      code: "organization.position.read",
      resource_type: "position",
      action: "read",
      scope: "workspace",
      status: "active",
    },
    {
      code: "organization.position.status",
      resource_type: "position",
      action: "change_status",
      scope: "resource",
      status: "active",
    },
    {
      code: "organization.assignment.write",
      resource_type: "organization_assignment",
      action: "write",
      scope: "resource",
      status: "active",
    },
    {
      code: "organization.assignment.read",
      resource_type: "organization_assignment",
      action: "read",
      scope: "resource",
      status: "active",
    },
    {
      code: "authorization.role.create",
      resource_type: "role",
      action: "create",
      scope: "workspace",
      status: "active",
    },
    {
      code: "authorization.role.read",
      resource_type: "role",
      action: "read",
      scope: "workspace",
      status: "active",
    },
    {
      code: "authorization.role.status",
      resource_type: "role",
      action: "change_status",
      scope: "resource",
      status: "active",
    },
    {
      code: "authorization.binding.create",
      resource_type: "role_binding",
      action: "create",
      scope: "workspace",
      status: "active",
    },
    {
      code: "authorization.binding.revoke",
      resource_type: "role_binding",
      action: "revoke",
      scope: "resource",
      status: "active",
    },
    {
      code: "authorization.effective_role.read",
      resource_type: "effective_role",
      action: "read",
      scope: "resource",
      status: "active",
    },
    {
      code: "authorization.role_permission.read",
      resource_type: "role_permission",
      action: "read",
      scope: "resource",
      status: "active",
    },
    {
      code: "authorization.role_permission.manage",
      resource_type: "role_permission",
      action: "manage",
      scope: "resource",
      status: "active",
    },
  ],
  page_resources: [
    {
      page_resource_id: "80000000-0000-4000-8000-000000000001",
      page_key: "auth.login",
      route: "/login",
      component_key: "LoginPage",
      layout_key: "layout.public",
      access_level: "public",
      permission_code: null,
      resource_version: 1,
      status: "active",
    },
    {
      page_resource_id: "80000000-0000-4000-8000-000000000002",
      page_key: "workspace.overview",
      route: "/workspace/overview",
      component_key: "WorkspaceOverviewPage",
      layout_key: "layout.workspace",
      access_level: "authorized",
      permission_code: "workspace.overview.access",
      resource_version: 1,
      status: "active",
    },
    {
      page_resource_id: "80000000-0000-4000-8000-000000000003",
      page_key: "workspace.members",
      route: "/workspace/members",
      component_key: "WorkspaceMembersPage",
      layout_key: "layout.workspace",
      access_level: "authorized",
      permission_code: "workspace.members.access",
      resource_version: 1,
      status: "active",
    },
    {
      page_resource_id: "80000000-0000-4000-8000-000000000004",
      page_key: "organization.structure",
      route: "/workspace/organization",
      component_key: "WorkspaceOrganizationPage",
      layout_key: "layout.workspace",
      access_level: "authorized",
      permission_code: "organization.structure.access",
      resource_version: 1,
      status: "active",
    },
    {
      page_resource_id: "80000000-0000-4000-8000-000000000005",
      page_key: "system.runtime",
      route: "/status",
      component_key: "StatusPage",
      layout_key: "layout.workspace",
      access_level: "authorized",
      permission_code: "system.runtime.access",
      resource_version: 1,
      status: "active",
    },
  ],
  api_resources: [
    {
      api_resource_id: "81000000-0000-4000-8000-000000000001",
      api_key: "system.health.live",
      operation_id: "getLiveness",
      method: "GET",
      path_pattern: "/api/v1/health/live",
      access_level: "public",
      permission_code: null,
      risk_level: "low",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000002",
      api_key: "system.health.ready",
      operation_id: "getReadiness",
      method: "GET",
      path_pattern: "/api/v1/health/ready",
      access_level: "public",
      permission_code: null,
      risk_level: "low",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000003",
      api_key: "identity.account.register",
      operation_id: "registerPersonalAccount",
      method: "POST",
      path_pattern: "/api/v1/auth/register",
      access_level: "public",
      permission_code: null,
      risk_level: "normal",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000004",
      api_key: "identity.session.login",
      operation_id: "loginWithPassword",
      method: "POST",
      path_pattern: "/api/v1/auth/login",
      access_level: "public",
      permission_code: null,
      risk_level: "normal",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000005",
      api_key: "identity.session.logout",
      operation_id: "logoutCurrentSession",
      method: "POST",
      path_pattern: "/api/v1/auth/logout",
      access_level: "authenticated",
      permission_code: null,
      risk_level: "low",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000006",
      api_key: "identity.context.read",
      operation_id: "getAuthenticationContext",
      method: "GET",
      path_pattern: "/api/v1/auth/context",
      access_level: "authenticated",
      permission_code: null,
      risk_level: "low",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000007",
      api_key: "workspace.accessible.list",
      operation_id: "listAccessibleWorkspaces",
      method: "GET",
      path_pattern: "/api/v1/workspaces",
      access_level: "authenticated",
      permission_code: null,
      risk_level: "low",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000008",
      api_key: "workspace.enterprise.create",
      operation_id: "createEnterpriseWorkspace",
      method: "POST",
      path_pattern: "/api/v1/workspaces/enterprise",
      access_level: "authorized",
      permission_code: "enterprise.workspace.create",
      risk_level: "normal",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000009",
      api_key: "workspace.invitation.create",
      operation_id: "inviteEnterpriseWorkspaceMember",
      method: "POST",
      path_pattern: "/api/v1/workspaces/{workspace_id}/invitations",
      access_level: "authorized",
      permission_code: "workspace.member.invite",
      risk_level: "normal",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000010",
      api_key: "workspace.invitation.accept",
      operation_id: "acceptEnterpriseWorkspaceInvitation",
      method: "POST",
      path_pattern: "/api/v1/workspaces/invitations/{invitation_id}/accept",
      access_level: "authorized",
      permission_code: "enterprise.invitation.accept",
      risk_level: "normal",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000011",
      api_key: "workspace.context.switch",
      operation_id: "switchWorkspaceContext",
      method: "POST",
      path_pattern: "/api/v1/workspaces/{workspace_id}/switch",
      access_level: "authorized",
      permission_code: "workspace.context.switch",
      risk_level: "low",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000012",
      api_key: "workspace.membership.leave",
      operation_id: "leaveEnterpriseWorkspace",
      method: "POST",
      path_pattern: "/api/v1/workspaces/{workspace_id}/leave",
      access_level: "authorized",
      permission_code: "workspace.membership.leave",
      risk_level: "high",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000013",
      api_key: "workspace.member.disable",
      operation_id: "disableEnterpriseWorkspaceMember",
      method: "POST",
      path_pattern: "/api/v1/workspaces/{workspace_id}/members/{account_id}/disable",
      access_level: "authorized",
      permission_code: "workspace.member.disable",
      risk_level: "high",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000014",
      api_key: "workspace.member.list",
      operation_id: "listEnterpriseWorkspaceMembers",
      method: "GET",
      path_pattern: "/api/v1/workspaces/{workspace_id}/members",
      access_level: "authorized",
      permission_code: "workspace.member.read",
      risk_level: "normal",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000015",
      api_key: "workspace.entitlement.read",
      operation_id: "getWorkspaceEntitlement",
      method: "GET",
      path_pattern: "/api/v1/workspaces/{workspace_id}/entitlements",
      access_level: "authorized",
      permission_code: "workspace.entitlement.read",
      risk_level: "low",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000016",
      api_key: "workspace.open_api.manage",
      operation_id: "setWorkspaceOpenApiFeature",
      method: "POST",
      path_pattern: "/api/v1/workspaces/{workspace_id}/entitlements/features/open-api",
      access_level: "authorized",
      permission_code: "workspace.open_api.manage",
      risk_level: "high",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000017",
      api_key: "organization.department.create",
      operation_id: "createEnterpriseDepartment",
      method: "POST",
      path_pattern: "/api/v1/workspaces/{workspace_id}/organization/departments",
      access_level: "authorized",
      permission_code: "organization.department.create",
      risk_level: "normal",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000018",
      api_key: "organization.department.list",
      operation_id: "listEnterpriseDepartments",
      method: "GET",
      path_pattern: "/api/v1/workspaces/{workspace_id}/organization/departments",
      access_level: "authorized",
      permission_code: "organization.department.read",
      risk_level: "normal",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000019",
      api_key: "organization.department.move",
      operation_id: "moveEnterpriseDepartment",
      method: "POST",
      path_pattern:
        "/api/v1/workspaces/{workspace_id}/organization/departments/{department_id}/move",
      access_level: "authorized",
      permission_code: "organization.department.move",
      risk_level: "high",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000020",
      api_key: "organization.department.status",
      operation_id: "setEnterpriseDepartmentStatus",
      method: "POST",
      path_pattern:
        "/api/v1/workspaces/{workspace_id}/organization/departments/{department_id}/status",
      access_level: "authorized",
      permission_code: "organization.department.status",
      risk_level: "high",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000021",
      api_key: "organization.position.create",
      operation_id: "createEnterprisePosition",
      method: "POST",
      path_pattern: "/api/v1/workspaces/{workspace_id}/organization/positions",
      access_level: "authorized",
      permission_code: "organization.position.create",
      risk_level: "normal",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000022",
      api_key: "organization.position.list",
      operation_id: "listEnterprisePositions",
      method: "GET",
      path_pattern: "/api/v1/workspaces/{workspace_id}/organization/positions",
      access_level: "authorized",
      permission_code: "organization.position.read",
      risk_level: "normal",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000023",
      api_key: "organization.position.status",
      operation_id: "setEnterprisePositionStatus",
      method: "POST",
      path_pattern: "/api/v1/workspaces/{workspace_id}/organization/positions/{position_id}/status",
      access_level: "authorized",
      permission_code: "organization.position.status",
      risk_level: "high",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000024",
      api_key: "organization.assignment.write",
      operation_id: "assignEnterpriseMemberOrganization",
      method: "PUT",
      path_pattern: "/api/v1/workspaces/{workspace_id}/organization/members/{account_id}",
      access_level: "authorized",
      permission_code: "organization.assignment.write",
      risk_level: "high",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000025",
      api_key: "organization.assignment.read",
      operation_id: "getEnterpriseMemberOrganization",
      method: "GET",
      path_pattern: "/api/v1/workspaces/{workspace_id}/organization/members/{account_id}",
      access_level: "authorized",
      permission_code: "organization.assignment.read",
      risk_level: "normal",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000026",
      api_key: "authorization.role.create",
      operation_id: "createEnterpriseRole",
      method: "POST",
      path_pattern: "/api/v1/workspaces/{workspace_id}/roles",
      access_level: "authorized",
      permission_code: "authorization.role.create",
      risk_level: "high",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000027",
      api_key: "authorization.role.list",
      operation_id: "listEnterpriseRoles",
      method: "GET",
      path_pattern: "/api/v1/workspaces/{workspace_id}/roles",
      access_level: "authorized",
      permission_code: "authorization.role.read",
      risk_level: "normal",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000028",
      api_key: "authorization.role.status",
      operation_id: "setEnterpriseRoleStatus",
      method: "POST",
      path_pattern: "/api/v1/workspaces/{workspace_id}/roles/{role_id}/status",
      access_level: "authorized",
      permission_code: "authorization.role.status",
      risk_level: "high",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000029",
      api_key: "authorization.binding.create",
      operation_id: "bindEnterpriseRole",
      method: "POST",
      path_pattern: "/api/v1/workspaces/{workspace_id}/roles/bindings",
      access_level: "authorized",
      permission_code: "authorization.binding.create",
      risk_level: "high",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000030",
      api_key: "authorization.binding.revoke",
      operation_id: "revokeEnterpriseRoleBinding",
      method: "POST",
      path_pattern: "/api/v1/workspaces/{workspace_id}/roles/bindings/{binding_id}/revoke",
      access_level: "authorized",
      permission_code: "authorization.binding.revoke",
      risk_level: "high",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000031",
      api_key: "authorization.effective_role.read",
      operation_id: "getEffectiveEnterpriseRoles",
      method: "GET",
      path_pattern: "/api/v1/workspaces/{workspace_id}/roles/effective/{account_id}",
      access_level: "authorized",
      permission_code: "authorization.effective_role.read",
      risk_level: "normal",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000032",
      api_key: "authorization.role_permission.read",
      operation_id: "listEnterpriseRolePermissions",
      method: "GET",
      path_pattern: "/api/v1/workspaces/{workspace_id}/roles/{role_id}/permissions",
      access_level: "authorized",
      permission_code: "authorization.role_permission.read",
      risk_level: "high",
      status: "active",
    },
    {
      api_resource_id: "81000000-0000-4000-8000-000000000033",
      api_key: "authorization.role_permission.manage",
      operation_id: "replaceEnterpriseRolePermissions",
      method: "PUT",
      path_pattern: "/api/v1/workspaces/{workspace_id}/roles/{role_id}/permissions",
      access_level: "authorized",
      permission_code: "authorization.role_permission.manage",
      risk_level: "critical",
      status: "active",
    },
  ],
  menus: [
    {
      menu_id: "82000000-0000-4000-8000-000000000001",
      menu_key: "navigation.workspace",
      parent_menu_key: null,
      name: "空间管理",
      menu_type: "directory",
      page_resource_id: null,
      permission_code: null,
      icon_key: null,
      sort_order: 100,
      source: "system",
      status: "active",
    },
    {
      menu_id: "82000000-0000-4000-8000-000000000002",
      menu_key: "navigation.workspace.overview",
      parent_menu_key: "navigation.workspace",
      name: "空间总览",
      menu_type: "page",
      page_resource_id: "80000000-0000-4000-8000-000000000002",
      permission_code: "workspace.overview.access",
      icon_key: "layout-dashboard",
      sort_order: 100,
      source: "system",
      status: "active",
    },
    {
      menu_id: "82000000-0000-4000-8000-000000000003",
      menu_key: "navigation.workspace.members",
      parent_menu_key: "navigation.workspace",
      name: "成员管理",
      menu_type: "page",
      page_resource_id: "80000000-0000-4000-8000-000000000003",
      permission_code: "workspace.members.access",
      icon_key: "users-round",
      sort_order: 200,
      source: "system",
      status: "active",
    },
    {
      menu_id: "82000000-0000-4000-8000-000000000004",
      menu_key: "navigation.workspace.organization",
      parent_menu_key: "navigation.workspace",
      name: "组织架构",
      menu_type: "page",
      page_resource_id: "80000000-0000-4000-8000-000000000004",
      permission_code: "organization.structure.access",
      icon_key: "network",
      sort_order: 300,
      source: "system",
      status: "active",
    },
    {
      menu_id: "82000000-0000-4000-8000-000000000005",
      menu_key: "navigation.workspace.status",
      parent_menu_key: "navigation.workspace",
      name: "运行状态",
      menu_type: "page",
      page_resource_id: "80000000-0000-4000-8000-000000000005",
      permission_code: "system.runtime.access",
      icon_key: "activity",
      sort_order: 400,
      source: "system",
      status: "active",
    },
  ],
} as const;

export type PageResource = (typeof resourceRegistry.page_resources)[number];
export type MenuResource = (typeof resourceRegistry.menus)[number];
